# Dependencies
markdown:            kramdown
highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
name:               MetaCrazie
baseurl:             http://metacrazie.github.io/
